language: go
sudo: required
dist: xenial

services:
  - docker

go:
  - 1.12.x

env:
  global:
    - GO111MODULE=on

install: true

cache:
  directories:
    - $GOPATH/pkg/mod

jobs:
  include:
    - stage: test
      name: "Lint"
      script: make lint
    - name: "Unit tests"
      script: make test
    - stage: build
      name: "Build"
      script: make build

# safelist
branches:
  only:
    - master

deploy:
  - provider: script
    script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && make docker
    on:
      branch: master

notifications:
  email: false
