apiVersion: skaffold/v1beta4
kind: Config
build:
  artifacts:
    - image: github.com/smoya/ratio
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - deploy/kubernetes/*
