apiVersion: v1
kind: Service
metadata:
  name: ratio
  labels:
    app: ratio
spec:
  ports:
      - name: grpc
        port: 50051
        targetPort: 50051
        protocol: TCP
  selector:
    app: ratio